### PR TITLE
Update to 0.3.0

### PR DESCRIPTION
**Pull request by mariusvniekerk**

### CODE REVIEW

**Comment by mrocklin** [comment]
The SHA is the same

**Comment by mariusvniekerk** [comment]
yeah i was basically being lazy and wanted the CI to just tell me

**Comment by mrocklin** [comment]
Someone should make a bot that scrapes PyPI for updates and, if turned on by an authorized user, just does the version bump automatically.

**Comment by mariusvniekerk** [comment]
there is something like that that is specced for the GSOC proposal

**Comment by mariusvniekerk** [comment]
@conda-forge-admin , please rerender

**Comment by CJ-Wright** [comment]
@mrocklin https://github.com/regro/cf-graph/pull/1 (auto PRs version bumps into feedstocks, maintainers still need to review/merge)

**Comment by mariusvniekerk** [comment]
@mrocklin ready to merge

**Pull request merged**
